### ISSUE TITLE
Set up templates for ETL of structured data

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WRODataPlatform#12]
Users will upload files via CKAN. If these contain structured data, a possible next step will be to ETL them into a database schema (BigQuery) using GCP Workflow or Dataflow.

We need to understand these processes, figure out some general patterns using GCP tools and develop templates so that data owners can run the migrations or transformations themselves.

**Comment by gubuntu** [comment]
This is a good example: https://github.com/kartoza/WRODataPlatform/issues/3#issuecomment-1119622271. It is more complex than the simple case of a spreadsheet with one table, but it is a real scenario so try it out as a test case, by getting the component tables into BigQuery in a usable structure. 

Ensure the final tables are registered in CKAN along with changes to metadata. Establish a procedure for handling data and metadata records for this standard scenario where you first have a raw data set uploaded to GCS via CKAN and described via a metadata record, then you have the same data set  now in a structured form in an RDBMS. How should CKAN records reflect this?

**Comment by vermeulendivan** [comment]
This has been done.

Bucket trigger flow diagram
![Flow_diagram_pipeline drawio](https://user-images.githubusercontent.com/79740955/190618120-1ae63c2a-2027-451f-a468-234e82b42ded.png)

NASA POWER downloader flow diagram
![Weather_data_download drawio](https://user-images.githubusercontent.com/79740955/190618131-98de9009-76c7-409e-b2b7-c61fd950d0ea.png)
