### ISSUE TITLE
initiate upload by importing metadata 

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WRODataPlatform#23]
As requested by @MikeSilberbauer today, enable metadata upload as an alternative to capturing the form. 

Possible scenario:

- User chooses to upload data and is presented with the metadata form
- we add a new button at the top 'I have metadata to upload'
- Click the button to upload an ISO 19115 XML file
- System parses the uploaded file and populates the form
- User can now modify the form if necessary and move to data upload step as before

**Comment by MikeSilberbauer** [comment]
That approach makes sense.
