### ISSUE TITLE
staging v production

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WRODataPlatform#30]
We need a minimal production environment asap that the team can trust and use for data set uploads and metadata capture. 

We should have a staging environment as well where we can test and stage new developments before deploying to production.

**Comment by Mohab25** [comment]
@gubuntu added the necessary docker/compose files for a dockerized version of the WRO that represents a minimal production unit, being tested and the site found to be running
 https://github.com/kartoza/WRODataPlatform/pull/33#issue-1286789797

**Comment by mikev3003** [comment]
@Mohab25 The CKAN site [http://34.71.13.135/] isn't working very nicely at the moment, unable to upload things like logos and do edits, often timing out after a user action. Maps are also not there. Can you please assist? Thanks

**Comment by Mohab25** [comment]
@mikev3003 made few edits, please give it a test,

**Comment by mikev3003** [comment]
thanks @Mohab25 
Date reference (to):
Data reference (from):
Do not seem to be working when I enter a range 1950/01/01 - 1999/12/31
![20220629_Capture](https://user-images.githubusercontent.com/93324774/176423562-4e3d126b-f480-4f2a-abae-8bda52908030.JPG)

Also please switch these two so 'from' appears first (and not the '(to)' date)

When there is an error and resubmission, the form forgets if 'Is this person a contact person...' and 'Did the author/contact organisation....' are checked (I remember we chatted about this last time but can't remember if it is possible to change)

**Comment by mikev3003** [comment]
@Mohab25 Please assist with these cosmetic edits for the metdata capture form: https://www.dropbox.com/s/j75srl1nw7r8l0z/20220629_CKAN%20edit%20requests.pdf?dl=0
(sorry its an occupational hazard from being in academia :-) )

**Comment by Mohab25** [comment]
@mikev3003 Ok professor give a test, for the spelling/ punctuation parts i'm also one of the guys who feel the itch, but under the pressure of getting other parts running i allow myself to give it a go :-) , 
please keep testing so we can finalize the form part and move to the next phase.   
thanks.

**Comment by Christiaan34** [comment]
Thanks @mikev3003, pasting the link in my browser works

**Comment by mikev3003** [comment]
@Mohab25 bugs in first page look like they are sorted out - thanks a million. For the actual data upload page, after I select file and click 'finish' it gives a 'this site cannot be reached' message. File is over 1 gb https://www.dropbox.com/s/sie9vzwpuc12xls/weather.csv?dl=0

**Comment by Christiaan34** [comment]
Sorry.. I have forgotten my password.. When I click the 'Forgot password' tab and enter my email, it gives the error: 'Error sending the email. Try again later or contact an administrator for help'

**Comment by Mohab25** [comment]
@mikev3003 just adjust the max upload size, can you give it a test, meanwhile i will be working with the progress bar
thanks,

**Comment by Christiaan34** [comment]
@Mohab25 the password reset is not working yet, could you please assist?

**Comment by Mohab25** [comment]
@Christiaan34 were you a site administrator ?

**Comment by mikev3003** [comment]
@Mohab25 @Christiaan34 is testing the site as a 'regular user'

**Comment by Mohab25** [comment]
ok just sent a password, @mikev3003 as a system admin you can reset passwords for different users, if you went to ckan_site_url/user you will see a list of users, click on one, then manage and you will have the users info to edit.

**Comment by mikev3003** [comment]
@Mohab25 I'm still not able to upload the file and still getting a 'this site cannot be reached message'

**Comment by mikev3003** [comment]
@Mohab25
![20220701_Capture1](https://user-images.githubusercontent.com/93324774/176904270-208cf0a3-9592-4116-bb15-0f9fb031084c.JPG)
![20220701_Capture2](https://user-images.githubusercontent.com/93324774/176904281-6e209b3f-8252-45e7-a574-514fc73ff445.JPG)

**Comment by Christiaan34** [comment]
I could upload a csv file without experiencing any errors.

**Comment by mikev3003** [comment]
@Christiaan34 thanks. I also managed with a smaller file. If you get a chance could you try uploading this one: https://www.dropbox.com/s/sie9vzwpuc12xls/weather.csv?dl=0 (it's 1.7 gb)

**Comment by Mohab25** [comment]
@mikev3003 i just uploaded a 1.1 GB file to the same dataset @Christiaan34 created  for testing and will soon going to delete it, can you re-upload the file and comment, 
thanks

**Comment by mikev3003** [comment]
@Mohab25 will it be possible to link the CKAN site to https://www.waterresearchobservatory.org/upload-data today? I need to submit a progress report by the end of the day and it will be great if readers can click on the link to see the data uploading and discovery platform

**Comment by Mohab25** [comment]
@tharanathkartoza @mikev3003 is referring to linking WRO Google VM instance to the above domain name, can we get into this today? 
thanks

**Comment by tharanathkartoza** [comment]
Hi Micheal,
As we could see that the domain and website [waterresearchobservatory.org](http://waterresearchobservatory.org/) is not managed from our end, it is not possible to link the CKAN site to https://www.waterresearchobservatory.org/upload-data.
The possible solution here is to add a subdomain say https://ckan.waterresearchobservatory.org/ and point it to the IP 34.71.13.135 and then set a redirection to the path from the webserver where the domain [waterresearchobservatory.org](http://waterresearchobservatory.org/) is hosted.

**Comment by mikev3003** [comment]
@tharanathkartoza since I manage the wateresearchobservatory domain through Google sites does that not mean it can be linked directly to IP 34.71.13.135?

**Comment by tharanathkartoza** [comment]
@mikev3003 Yes, from google sites, it should be possible to link directly to IP or an url.

**Comment by tharanathkartoza** [comment]
@mikev3003 can you please add the subdomain upload-data.waterresearchobservatory.org and map to IP 34.71.13.135.

**Comment by mikev3003** [comment]
@tharanathkartoza thanks
@PKhoboko can you please come and assist me with this?

**Comment by tharanathkartoza** [comment]
@mikev3003, SSL certificate has been installed.

**Comment by mikev3003** [comment]
Great, thanks @tharanathkartoza

**Comment by mikev3003** [comment]
@Mohab25 the organisation logos aren't showing, can you please take a look?

**Comment by Mohab25** [comment]
@mikev3003 fixed, we needed to change the CKAN site's url to the new domain.

**Comment by Mohab25** [comment]
having testing, staging and production instance requires 3 instances in GCP, for cost reasons, this is halted at the moment.

**Comment by mikev3003** [comment]
Noted thanks @Mohab25
