### ISSUE TITLE
Symbologies for weather data

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/WRODataPlatform#41]
Provide suggestions for the weather data symbologies. Examples below:
Rainfall:
![image](https://user-images.githubusercontent.com/79740955/184324237-4b0bb353-1730-4951-981f-6d1ecdedbdd8.png)

Temperature:
![image](https://user-images.githubusercontent.com/79740955/184324322-1ad85be9-d8f0-4899-bd05-3e16043179c2.png)

**Comment by vermeulendivan** [comment]
Hi @mikev3003 Here are my suggestions for symbologies to use for the nasa power weather data (or other weather data sources). The examples uses the same raster, just used so that I can display the symbologies itself. Any changes are welcome!

Earth skin temperature, temperature, temperature maximum, temperature minimum, and wet temperature. Focus on red:

![image](https://user-images.githubusercontent.com/79740955/184365312-c3d2d964-c358-496b-ad60-2594d97778fd.png)

Cloud amount, frost/dew, precipitation average, precipitation average sum, relative humidity, and specific humidity. Focus on blue:

![image](https://user-images.githubusercontent.com/79740955/184365337-723018a9-12f7-409e-a978-ba8462aef23a.png)

Clear sky surface PAR, sky surface PAR total, and sky surface shortwave irradiance. Focus on orange/yellow.

![image](https://user-images.githubusercontent.com/79740955/184365366-19b8c2f1-50a2-4795-ac39-a66020ac0f79.png)

Profile soil moisture, root soil wetness, and surface soil wetness. These can go with blue, or focus on green:

![image](https://user-images.githubusercontent.com/79740955/184365387-2703be74-172a-41c4-80fa-c4e706e647d4.png)

Windspeed (2m) and windspeed (10m): Focus on blue-green-red colouring – were not sure what to use here, but this is a similar symbology based on online checks other people use for windspeed:
![image](https://user-images.githubusercontent.com/79740955/184365419-0663fef0-2dd6-4864-9f3f-b8abb385130b.png)

**Comment by vermeulendivan** [comment]
@mikev3003 Can I close this? If I'm not mistaken, we decided a while back to no longer do this as its too many rasters to create (~300k).

**Comment by mikev3003** [comment]
@vermeulendivan yes thanks

**Comment by vermeulendivan** [comment]
This will be closed as its no longer viable due to the large number of datasets.
