### ISSUE TITLE
Move ckan platform to a secure site (https)

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/WRODataPlatform#42]
Client wants to start  doing testing of the platform, but we first need to move the ckan site to secure. This needs to be done ASAP.

**Comment by Mohab25** [comment]
@tharanathkartoza this is the same as #30, please look into this asap, if linkage between Ckan and google sites takes time, please look at the GCP VM configuration.

**Comment by Mohab25** [comment]
the site is now working under https://data.waterresearchobservatory.org

**Comment by Mohab25** [comment]
the site is now working under https://data.waterresearchobservatory.org/
