### ISSUE TITLE
GPS co-ordinates are not retained when editing a dataset

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/WRODataPlatform#51]
GPS co-ordinates are not retained when editing a dataset

@mikev3003 This is related to ckan I'm assuming?

**Comment by mikev3003** [comment]
@vermeulendivan yes, 'Geographic location or bounding box coordinates'

**Comment by Mohab25** [comment]
@vermeulendivan  @mikev3003 please give this issue a check and revert back, fixed with the latest commit.
![dataset sptial extent with edit form](https://user-images.githubusercontent.com/58084234/192317830-f17ba398-848e-45e6-b444-441512d23862.png)

**Comment by Mohab25** [comment]
@mikev3003

**Comment by Mohab25** [comment]
@mikev3003 please retest this and close the issue if it worked as expected.

**Comment by mikev3003** [comment]
@Mohab25 thanks, gps co-ordinates are now retained
