### ISSUE TITLE
User log in issue

### ISSUE THREAD

**Issue by Christiaan34** [kartoza/WRODataPlatform#56]
Lesego Gaegane is the project manager for the Water Research Commission Siltation programme that will generated a lot of data. Therefore, Lesego is a very important tester for the WRC and is trying to upload a test dataset.

She is experiencing an issue when she tries to log in. Her comment is: "I have registered, however as soon as I’m logged out I struggle to log back into my account, and then I have to re-register again".

@Mohab25 , it will be greatly appreciated if you could assist with providing her access to the WRO so that she can upload a test dataset.

**Comment by Mohab25** [comment]
Credentials are sent to Lesego Gaegane, to automate the process, we need to accelerate the SMTP service attachment to the cloud VM,
